---

- name: Check if APT can use HTTPS
  stat: path=/usr/lib/apt/methods/https
  register: https_support

- name: Enable HTTPS links for APT
  apt: name=apt-transport-https state=present update_cache=yes
  when: not https_support.stat.exists

- name: Add Docker APT repository key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: Enable Docker APT repository key
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present update_cache=yes

- name: Install Docker
  apt: name=lxc-docker state=latest

# Required by Ansible's "docker" command
# (fixed docker-py version due to this bug: https://github.com/ansible/ansible/issues/10879)
- name: Install python Docker client
  pip: name=docker-py state=present version=1.1.0

- name: Start elasticsearch
  docker: image=barnybug/elasticsearch ports=9200:9200,9300:9300
